
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: visitantes_development

production:
  <<: *default
  host: 10.0.0.13
  database: visitantes

#development_cimavnetmultix:
#  adapter: mysql2
#  encoding: utf8
#  pool: 5
#  username: root
#  socket: /tmp/mysql.sock
#  database: cimavnetmultix_development

development_cimavnetmultix:
  adapter: mysql2
  host: 10.0.0.13
  encoding: utf8
  pool: 5
  username: netmultix
  password: <%= ENV['CIMAVNETMULTIX_DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock
  database: cimavnetmultix

production_cimavnetmultix:
  adapter: mysql2
  host: 10.0.0.13
  encoding: utf8
  pool: 5
  username: netmultix
  password: <%= ENV['CIMAVNETMULTIX_DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock
  database: cimavnetmultix

visitas_programadas_production:
  adapter: mysql2
  host:  fermi.cimav.edu.mx
  encoding: utf8
  pool: 5
  username: admin
  password: <%= ENV['VISITAS_PRODUCTION_PASSWORD'] %>
  socket: /tmp/mysql.sock
  database: visitas_development

visitas_programadas_development:
  adapter: mysql2
  host:  10.0.3.234
  encoding: utf8
  pool: 5
  username: calderon
  password: <%= ENV['VISITAS_DEVELOPMENT_PASSWORD'] %>
  socket: /tmp/mysql.sock
  database: visitas_development
