# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7835e4ae4366c6024ea59c492b1b866f6558c7d43de3475e8e2003275b368359489fb36ee24956ecd693f47392dde9ad564a4a02d6134c5afa48829691e2f804

test:
  secret_key_base: 16d3e0918cdf32620ca8aee57a81a2078acf1be9dd9367b55c4fe5950cba164edc76cb60ce51bcc0aa696a3337441134ba8b46d94f6dce146d160d027a22bf35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 7835e4ae4366c6024ea59c492b1b866f6558c7d43de3475e8e2003275b368359489fb36ee24956ecd693f47392dde9ad564a4a02d6134c5afa48829691e2f804
